### ISSUE TITLE
[Suggestion] Connected Block Textures support

### ISSUE THREAD

**Issue by gdude2002** [Wurst-Imperium/Mo-Glass#10]
It might be nice to include support for [the Connected Block Textures mod](https://www.curseforge.com/minecraft/mc-mods/connected-block-textures), assuming @Nuclearfarts gets another CF release out at some point.

I believe this works using Optifine's resource pack-based method.

**Comment by Alexander01998** [comment]
Apparently that mod doesn't exist anymore, and neither does the @Nuclearfarts GitHub account. Let's close this issue then.

I did look at their code some time in 2021 and found that the mod wasn't really made for stairs. Getting it to work with Mo Glass would have required pretty large changes on their end.
