### ISSUE TITLE
[Feature Request] Support with Better Slabs

### ISSUE THREAD

**Issue by Abbanon** [Wurst-Imperium/Mo-Glass#11]
I'm humbly requesting support with the Better Slabs mod (https://www.curseforge.com/minecraft/mc-mods/better-slabs).
Currently, trying to use the two mods together causes strange visual bugs when placing Mo Glass slabs vertically.
Would adding support be possible in a future version?

**Comment by Alexander01998** [comment]
Interesting. Could you post a screenshot showing what these visual bugs look like?

**Comment by Abbanon** [comment]
Here, I've taken some screenshots, but it also appears that there's more than just visual bugs. 
There's also a bunch of stuff in the log complaining about it, too (starting on line 436): https://paste.ee/p/aR12k

![Screenshot_2](https://user-images.githubusercontent.com/37251822/115977286-91f45480-a544-11eb-8030-fed06d271a43.png)
![Screenshot_1](https://user-images.githubusercontent.com/37251822/115977287-928ceb00-a544-11eb-9059-7641dabf9855.png)

**Comment by Micalobia** [comment]
A different mod, but I'm the developer of Full Slabs and am working on making this mod compatible with it in the next version if you're looking for alternatives.
