### ISSUE TITLE
Add block tags

### ISSUE THREAD

**Issue by Micalobia** [Wurst-Imperium/Mo-Glass#16]
Adding the slabs and stairs to the tags `#minecraft:slabs` and `#minecraft:stairs` would be a nice quality of life, as well as maybe making a unique tag such as `#mo_glass:glass_slabs` and `#mo_glass:glass_stairs`

**Comment by Alexander01998** [comment]
This has been implemented as of [Mo Glass 1.6](https://www.wimods.net/mo-glass/mo-glass-1-6/).
