### ISSUE TITLE
Visual Bug - Mo Glass v1.3 for MC 1.16.1

### ISSUE THREAD

**Issue by rxay579** [Wurst-Imperium/Mo-Glass#2]
Very nice mod and much appreciated!

Not sure if here or the Curseforge page is a better place to post this.

There seems to be a visual bug with Mo Glass v1.3 for MC 1.16.1 (haven't tested other versions) with stairs in admittedly weird positions.  Screenshot attached with areas circled in red.
![2020-07-17_00 21 12](https://user-images.githubusercontent.com/67221030/87751908-b99fda80-c7c4-11ea-95f5-3612c2acf5af.png)

**Comment by Alexander01998** [comment]
Thanks! I have fixed this in v1.4.

![2020-08-09_18 15 57](https://user-images.githubusercontent.com/10100202/89738443-ce485900-da78-11ea-86ac-77deab7e56f9.png)
