### ISSUE TITLE
Compatibility level set to JAVA_16

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Wurst-Imperium/Mo-Glass#20]
1.18-RC3 and RC4 server will not start with Compatibility level set to JAVA_16.
I was testing in my new mod pack, [99 Mods on the Wall: Fabric Edition](https://www.curseforge.com/minecraft/modpacks/ninety-nice-99-mods-on-the-wall-fabric-edition) to run on a server and got this message. I narrowed it down to Mo Glass and then tried to run the server with only Mo Glass and the error persisted.

> Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))

	- fabricloader 0.12.5
	- java 17
	- minecraft 1.18-rc.3
	- mo_glass 1.5-MC1.18-rc
[latest.log](https://github.com/Wurst-Imperium/Mo-Glass/files/7620385/latest.log)

[console_log.txt](https://github.com/Wurst-Imperium/Mo-Glass/files/7620402/console_log.txt)

**Comment by Alexander01998** [comment]
And of course, the moment I changed mixin compatibility back to Java 16, a new Fabric Loader version got released that now supports Java 17. Oh well. Either way it works now.

**Comment by ClaudiusMinimus** [comment]
Thanks! Works great!
