### ISSUE TITLE
Ice Slabs and Stairs [Idea]

### ISSUE THREAD

**Issue by SpiderKolo** [Wurst-Imperium/Mo-Glass#28]
I think suggestion is straight-forward, but just to add few details:
- There are three types of Ice, out of which only one is transparent and would need similar treatment as Glass
- Only one of those types can melt - in which case I think Slabs and Stairs should be able to be melted too for consistency

**Comment by Alexander01998** [comment]
Hi @SpiderKolo, thanks for your suggestion! However, Mo Glass is focused strictly on adding glass-based blocks. Ice stairs and slabs fall outside the project's scope and would probably be best suited for a separate mod dedicated to ice blocks.
