### ISSUE TITLE
World corruption

### ISSUE THREAD

**Issue by HostedByDev** [Wurst-Imperium/Mo-Glass#34]
When I install Mo Glass and use any fabric api, including the suggested 0.68.1 from the mo glass download page, my world becomes corrupted. My client is not running any mods and no other mods are running. 

I am running a fabric 1.19.3 server forget to mention that bit. The mod version and fabric api version match as 1.19.3.

I have included a screenshots of how it corrupts the world by replacing blocks and items. It also forces my client to crash even though I am giving it 15gb of ram on my last attempt. I am not sure what I am doing wrong or why it is behaving this way. 

![2023-06-09_22 43 46](https://github.com/Wurst-Imperium/Mo-Glass/assets/67978161/671967d6-f7a9-4615-aafd-19c01133e775)
![2023-06-09_22 43 50](https://github.com/Wurst-Imperium/Mo-Glass/assets/67978161/99cbb7ad-3a59-4197-b58b-3f04cfbba1f0)
![2023-06-09_22 44 05](https://github.com/Wurst-Imperium/Mo-Glass/assets/67978161/c63731d0-e25e-4fab-a049-93fda02e2b34)

**Comment by HostedByDev** [comment]
![2023-06-09_22 51 45](https://github.com/Wurst-Imperium/Mo-Glass/assets/67978161/6b028eea-606f-4467-a544-dc0ad4080770)

This is what the world should look like here.

**Comment by Alexander01998** [comment]
Hey @HostedByDev,

Thank you for reporting this issue and providing screenshots.

It's strange to see this kinds of corruption, as Mo Glass only adds a few new blocks and shouldn't be capable of causing world corruption issues by itself, especially not replacing non-glass blocks as shown in your screenshots.

I've been unable to replicate the problem you're encountering by installing Mo Glass with Fabric API version 0.68.1 on a Fabric 1.19.3 server. Could you please confirm one more time if you have any other mods running alongside Mo Glass?

If the client/server has absolutely no other mods installed, then it's also worth looking into whether the world had any prior issues or if using a fresh world still results in the same problem.

Also, could you check the crash logs and provide any extra information? They often provide helpful insights into what might be causing this issue.

We'll try to get to the bottom of this issue together!
