### ISSUE TITLE
Compatibility with Continuity/Connected Glass Textures?

### ISSUE THREAD

**Issue by Dumpling00** [Wurst-Imperium/Mo-Glass#36]
Please? That would be great. At least for the slabs? 

![image](https://github.com/Wurst-Imperium/Mo-Glass/assets/44829013/5e49b6c6-8ea8-4312-b506-6098f1e45e65)

Would love to have a floor or ceiling looking this clean. I tend to use slabs for floorings to make the ceilings look taller without going up a full block.

Thank you for your time and consideration.

**Comment by Alexander01998** [comment]
Hey @Dumpling00! As I understand it, this is something that would have to be implemented on Continuity's side. All of the connected textures mods I've seen so far don't seem to be built to handle stairs/slabs in general. So unfortunately there might not be anything I can do about it from Mo Glass's side.
