### ISSUE TITLE
Vertical Slab 

### ISSUE THREAD

**Issue by makumaku1974** [Wurst-Imperium/Mo-Glass#38]
Vertical Glass that offsets in any 90 degree angle
![image](https://github.com/user-attachments/assets/62380451-e008-4bec-998a-99f8902f8f16)

**Comment by Alexander01998** [comment]
Hey @makumaku1974! Thanks for the suggestion, but I'm afraid this is out of scope for Mo Glass. I'm trying to keep the mod very narrow and simple, like something that Mojang would add if they had the time. However, there are many great vertical slab mods already on [CurseForge](https://www.curseforge.com/minecraft/search?page=1&pageSize=20&sortType=1&class=mc-mods&search=vertical+slabs) and [Modrinth](https://modrinth.com/mods?q=vertical+slabs), some of which can even convert slabs from other mods to vertical slabs.
