### ISSUE TITLE
[Suggestion] Is it possible to apply Vanilla textures for all sides of blocks?

### ISSUE THREAD

**Issue by linzexin022** [Wurst-Imperium/Mo-Glass#8]
Hi there! I love your creative idea on glass variants! However, when I use my favorite texturepack and found some sides of blocks are not entirely applied with it. I think this may be caused by the difficulty of applying all vanilla textures to those glass variants. I don't know if it's possible to apply textures accurately to pixels (I'm a layman of modding). What do you think?
Another suggestion, could you add an item group of all your glass variants?

**Comment by supersaiyansubtlety** [comment]
I'm not involved in the development of this mod (I am a mod dev though), but my thoughts on this are:

It would have to transform the full-block-face textures that resourcepacks have for the vanilla glass block into all the possible shapes the sides of stairs can have. This would be the 'L' shape, the slab-side shape, and the quarter-face shape, ignoring rotations. 

There's no guarantee the textures generated by this transformation would look good, you'd have to use a heuristic approach and make assumptions such as that the full-block-face textures have a 1-pixel border and maybe a mark in each corner. 

This sounds to me like something that may just be too much effort for too little payoff. I'm not sure, there are libraries to help with this sort of thing, but it could easily end up being quite complex and yet not look that good for most resourcepacks.
